name: personal_porfolio
description: "Debdaru's Professional Portfolio"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/Bebas_Neue/
      - assets/data/
      - assets/Images/
      - assets/Playfair_Display_SC/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/Bebas_Neue/BebasNeue-Regular.ttf

    - family: PlayfairDisplaySC
      fonts:
        - asset: assets/Playfair_Display_SC/PlayfairDisplaySC-Regular.ttf
        - asset: assets/Playfair_Display_SC/PlayfairDisplaySC-Italic.ttf
          style: italic
        - asset: assets/Playfair_Display_SC/PlayfairDisplaySC-Bold.ttf
          weight: 700
        - asset: assets/Playfair_Display_SC/PlayfairDisplaySC-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/Playfair_Display_SC/PlayfairDisplaySC-Black.ttf
          weight: 900
        - asset: assets/Playfair_Display_SC/PlayfairDisplaySC-BlackItalic.ttf
          weight: 900
          style: italic
